/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class phylonet_coalescent_Polytree_PTNative */

#ifndef _Included_phylonet_coalescent_Polytree_PTNative
#define _Included_phylonet_coalescent_Polytree_PTNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     phylonet_coalescent_Polytree_PTNative
 * Method:    cppInit
 * Signature: (II[I[[J)V
 */
JNIEXPORT void JNICALL Java_phylonet_coalescent_Polytree_00024PTNative_cppInit
  (JNIEnv *, jclass, jint, jint, jintArray, jobjectArray);

/*
 * Class:     phylonet_coalescent_Polytree_PTNative
 * Method:    cppCompute
 * Signature: ([J[J[J)J
 */
JNIEXPORT jlong JNICALL Java_phylonet_coalescent_Polytree_00024PTNative_cppCompute
  (JNIEnv *, jclass, jlongArray, jlongArray, jlongArray);

/*
 * Class:     phylonet_coalescent_Polytree_PTNative
 * Method:    cppBatchCompute
 * Signature: ([J[[J[[J[[J)V
 */
JNIEXPORT void JNICALL Java_phylonet_coalescent_Polytree_00024PTNative_cppBatchCompute
  (JNIEnv *, jclass, jlongArray, jobjectArray, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
